### ISSUE TITLE
takeUntil(ngOnDestroy) not working in ngOnInit, Angular 13

### ISSUE THREAD

**Issue by 11mb** [cloudnc/ngx-observable-lifecycle#52]
Oddly when I setup the ngOnDestroy method in the ngOnInit method it won't work:

```
ngOnInit() {
    const {ngOnDestroy} = getObservableLifecycle(this);
    interval(400)
      .pipe(
        takeUntil(ngOnDestroy),
      )
      .subscribe(() => {
          console.log('interval');
        }
      );
  }
  ```
  
  ==> output: continued 'interval', also when component is destroyed
  
  When I put this exact code in the constructor of the component, the console.logging will stop when the component is destroyed.
  
  Experienced in Angular 13. ngx-observable-lifecycle: 2.1.3

**Comment by zakhenry** [comment]
This is expected behaviour because of how the `getObservableLifecycle` works under the hood. It patches the class at construction time which is why this won't work if called inside an ngOnInit hook.
